version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: email_gen_redis
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    container_name: email_gen_backend
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./frontend:/app/frontend
    environment:
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
    command: uvicorn main:app --host 0.0.0.0 --port 8000
  worker:
    build: ./backend
    volumes:
      - ./uploads:/app/uploads
    environment:
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - redis
      - backend
    command: celery -A tasks.celery_app worker --loglevel=info --concurrency=1
    deploy:
      replicas: 2
